### ISSUE TITLE
Add support for defining known configurations in provisioning.xml

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#140]
To specify more complex combinations, we should be able to package provisioning.xml within prospero and use something like:

```
- name: "eap-8.0-beta"
  galleonConfiguration: "galleon/eap-8.0-provisioning.xml"
  channelGavs:
  - "org.jboss.eap.channels:eap-8.0-beta"
  repositories:
  - id: "mrrc"
    url: "https://maven.repository.redhat.com/earlyaccess/all/" 
```
