### ISSUE TITLE
When using a custom fpl, it should be possible to specify channel and repositories using command parameters only.

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#152]
Currently when using a custom FPL, user has to provide a provision-config file with channels and repositories, eg:
```
./prospero.sh --dir=test --fpl=org.wildfly:wildfly-ee-galleon-pack --provision-config=wfly-config.yaml
```
where wfly-config.yaml contains:
```
channels:
  - url: "file:///path/to/repository"
repositories:
  - id: "central"
    url: "https://repo1.maven.org/maven2/"
  - id: "jboss-public"
    url: "https://repository.jboss.org/nexus/content/groups/public/"
```

Instead it should be possible to pass those via CLI paramaters like:
```
./prospero.sh --dir=test \
    --fpl=org.wildfly:wildfly-ee-galleon-pack \
    --channel=/path/to/channel.yaml\
    --remote-repositories=https://repo1.maven.org/maven2/,https://repository.jboss.org/nexus/content/groups/public/
```
