### ISSUE TITLE
Support multiple channels

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#170]
installer-config.yaml

```
---
manifests:
- url: "https://gitlab.cee.redhat.com/bspyrkos/channels-definitions/-/raw/main/eap-80-proposed/src/main/resources/channel.yaml"
- url: "file:///Users/spyrkob/workspaces/set/prospero/prospero/unprod_channel.yaml"
repositories:
- id: "central"
  url: "https://repo1.maven.org/maven2"
- id: "eap8-prod-repo"
  url: "http://eap-prod-reposilite.usersys.redhat.com/eap8-test-release/"
---
manifests:
- url: "https://gitlab.cee.redhat.com/bspyrkos/channels-definitions/-/raw/main/eap-80-proposed/src/main/resources/channel.yaml"
- url: "file:///Users/spyrkob/workspaces/set/prospero/prospero/unprod_channel.yaml"
repositories:
- id: "central"
  url: "https://repo1.maven.org/maven2"
- id: "eap8-prod-repo"
  url: "http://eap-prod-reposilite.usersys.redhat.com/eap8-test-release/"
```
