### ISSUE TITLE
Add support for versioned syntax of eap and wildfly installation types

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#40]
Adapt externalized versions so that new major/minor versions are detected based on available artifacts.

eg. `prospero-known-combintations.yaml` could define:
```
- name-pattern: "test"
  location: "org.prospero.test:test-feature-pack"
  channelGav: "org.prospero:test:test-channel"
  repositories:
  - id: "central"
    url: "https://repo1.maven.org/maven2/"
```
and following channel artifacts were present in the repository:
 * org.prospero:test:test-channel:1.0.0
 * org.prospero:test:test-channel:1.1.0
 * org.prospero:test:test-channel:2.0.0

User could then use any of `test-1.0`, `test-1.1` or `test-2.0` to select fpl to install.

Note, there would have to be a mechanism for changing definition in newer versions
