### ISSUE TITLE
Clarifying valid argument combinations

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#56]
@spyrkob can you help me understand what are expected valid combinations of arguments when provisioning a server?

Two options that work for me:

1. `prospero install --dir=eap --fpl=eap` -- this works with "well known" fpl shortcuts like "eap" or "wildfly"
2. `prospero install --dir=eap --fpl=org.jboss.eap:wildfly-ee-galleon-pack --channel-file=provision.json`

where the provision.json file looks like:

```
{
  "channels": [
    {"gav": "org.jboss.eap.channels:eap-8.0-beta:1.0.0.Beta-redhat-00001"}
  ],
  "repositories": [
    {
      "id": "central",
      "url": "https://repo1.maven.org/maven2/"
    },
    {
      "id": "mrrc",
      "url": "https://maven.repository.redhat.com/ga/"
    },
    {
      "id": "channel",
      "url": "file:///home/thofman/tmp/m2-repo"
    }
  ]
}
```

I suppose it should also be possible to not use the `--channel-file=provision.json` and specify everything via arguments? Right now `--channel-file` is required.

**Comment by TomasHofman** [comment]
Another fail on mine that I run into repeatedly is that I download the EAP maven repository zip from prod build, unzip it, and then try to use it as `--local-repo`. This fails with `Unable to resolve versions of org.jboss.eap.channels:eap-8.0-beta:yaml:channel:[1.0.0.Beta-redhat-00001,)`.

It doesn't work, because in local repositories Maven requires metadata files to be named differently (maven-metadata-local.xml) than in remote repositories (maven-metadata.xml), so the tool is unable to resolve version ranges (because the local metadata files are not there). One must remember to use the unzipped repo as a *remote* maven repository (configured via the json config, or via --channel-repo), even though it's on a local filesystem...

Is this something we should fix? What are the situations when a user might want to define the local repo? Only when doing offline installation? Do we need to ask prod to generate also the maven-metadata-local.xml files in the repo zips, so that version range resolutions can work in offline mode? Or user would always point to the local repository as to a remote repository (in offline mode), and the `--local-repo` argument would go away?

**Comment by spyrkob** [comment]
> I suppose it should also be possible to not use the --channel-file=provision.json and specify everything via arguments? Right now --channel-file is required.
For now `--channel-file` is the only way to alter repository/channel configuration. Configuring that via parameters might be a good improvement in future. 

> It doesn't work, because in local repositories Maven requires metadata files to be named differently
Yes, PROD will need to add metadata and channels file to the repository zips

> Is this something we should fix? What are the situations when a user might want to define the local repo? Only when doing offline installation?
Originally the local-repo was doubling up as option to use a maven cache to speed up rebuilds. However I think those two functions will need to be separated in GA - local-repo would add the repository as remote and something like --cache would add option to specify a local cache.

**Comment by TomasHofman** [comment]
OK, so the two currently valid options of install commands are:

* `prospero install --dir=<directory> --fpl=<well-known-name>`
* `prospero install --dir=<directory> --fpl=<G:A> --channel-file=<JSON provisioning file>`

Followup questions:

1. Would it be better to rename the `--channel-file` to something else? `--provisioning-file` or `--provisioning-config`? To me, the "channel file" term is already associated with the channel.yaml files used by the wildfly-channel library. I thing this will confuse people and will make it more difficult to write docs in an unambiguous manner. 
2. Since wildfly-channel already uses configuration file in YAML, would it be better to stick to YAML also for these prospero config files?
3. As there are at least above two configuration files (wildfly-channel YAML, prospero JSON/YAML) involved in provisioning, we could try to bring some kind of order in this, and define "named" schemata for them?

What I mean is that these config files could always start with "schemaName" and "schemaVersion" attributes, which would clearly define what a given file is. (wildfly-channel configs already have "schemaVersion", but that's sort of incomplete without also saying "version of WHICH schema?".

So we could have:
```yaml
schemaName: "wildfly-channel"
schemaVersion: "1.0.0" # already present
name: "Channel for org.jboss.eap:wildfly-ee-galleon-pack:pom:8.0.0.Beta-redhat-20220614\
  \ feature pack."
description: "Generated by org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin\
  \ at 2022-06-14T16:21:17.793742Z"
streams:
  - groupId: "antlr"
    artifactId: "antlr"
    version: "2.7.7.redhat-7"
  - ...
```

and then:

```yaml
schemaName: "prospero"
schemaVersion: "1.0.0"
channels:
    gav: "org.jboss.eap.channels:eap-8.0-beta:1.0.0.Beta-redhat-00001"
repositories:
  - "id": "central",
    "url": "https://repo1.maven.org/maven2/"
  - ...
```

and everyone is able to tell what the file is intended for.
