### ISSUE TITLE
`channel versions` doesn't print versions?

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#586]
From the usage I understand the `channel versions` should print versions of channels or manifests:

```
$ bin/jboss-eap-installation-manager.sh channel
...
Commands:
  add       Subscribes the installation to a new channel.
  remove    Unsubscribes the installation from a channel.
  list      Lists the channels used by the installation to get updates
  versions  Displays currently used versions of manifests from registered channels.
```

But it doesn't:

```
$ bin/jboss-eap-installation-manager.sh channel versions
Installed server components:
  * Manifest for EAP 8.0
```

**Comment by spyrkob** [comment]
It looks like the manifest doesn't provide the correct information in the `name` field

**Comment by TomasHofman** [comment]
So the maven artifact version should play no role here?

As I'm looking around the metadata, there is the `.installation/manifest_version.yaml` which contains maven coordinates:

```
---
schemaVersion: "1.0.0"
maven:
- groupId: "org.jboss.eap.channels"
  artifactId: "eap-8.0"
  version: "1.1.0.GA-redhat-00001"
  description: "Manifest for EAP 8.0"
```
