### ISSUE TITLE
Add ability to modify provisioning configuration when installing certain feature packs

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#599]
When adding some feature packs on top of existing installation, the provisioning configuration might need to be changed.

For instance when installing `org.wildfy:wildfly-galleon-pack` on top of server provisioned from `org.wildfly:wildfly-ee-galleon-pack`, the resulting provisioning configuration should replace the `org.wildfy:wildfly-galleon-pack` configuration with the new feature pack rather than listing both feature packs.

It should also be possible to install additional packages when adding feature packs.

The proposal is to add a `feature-pack-templates.yaml` configuration file with following schema:

```
schemaVersion: 1.0.0
feature-packs:
  - groupId: "org.groupId"
    artifactId: "artifactId"
    version: "[0,)"
    supports-customization: false
    requires-layers: false
    replaces-dependency: "org.groupId:artifactId"
   additional-packages:
    - example.package
```
