### ISSUE TITLE
Support properties in prospero-config.yaml

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#80]
`prospero-config.yaml` in .installation folder should allow use of `${jboss.home}` or similar to resolve to the server's installation root directory

**Comment by soul2zimate** [comment]
Do you mean the `--provision-config` argument ? From `.installtion` directory, I see only `installer-config.yaml` instead of `prospero-config.yaml`, but it seems it copies the content of `--provision-config` file.

For example I have such content passed to `--provision-config`:

```
---
channels:
- url: "file:/Users/chaowan/work/git/wildfly-extra/prospero/channel.yaml"
repositories:
- id: "central"
  url: "https://repo1.maven.org/maven2/"
- id: "eap8-prod-repo"
  url: "http://download.eng.pek2.redhat.com/brewroot/repos/jb-eap-8.0-maven-build/latest/maven/"
- id: "jboss-org"
  url: "https://repository.jboss.org/nexus/content/groups/public/"
```

There are `url` and `gav` for channel and `id` and `url` for repository, which needs to support properties like `${jboss.home}` ?
